import React from 'react';
import { Check } from 'lucide-react';

export const WhyRanked = ({ rank, reasons }) => {
  return (
    <div className="soc-card">
      <h2 className="section-title mb-0">Why is this incident ranked #{rank}?</h2>
      <p className="section-subtitle">
        Automated priority justification generated by backend analytics.
      </p>

      <div className="reasons-rows-group">
        {reasons.map((reason, idx) => (
          <div key={idx} className="reason-row-item">
            <Check className="reason-check-icon" size={16} />
            <span>{reason}</span>
          </div>
        ))}
      </div>
    </div>
  );
};
